{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ template "shipa.fullname" . }}-http-ingress
  labels: {{- include "shipa.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "shipa-nginx-ingress"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "shipa.fullname" . }}-api
              servicePort: {{ .Values.shipaApi.port }}
